/** `dotme init` — create ~/.me, interactively or with --sample data. */

import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import * as readline from "node:readline/promises";
import {
  CHANGELOG_FILE,
  appendChangelog,
  defaultPermissions,
  meDir,
  meExists,
  saveManifest,
} from "../core/me.js";
import {
  GITIGNORE,
  memoryMd,
  preferencesMd,
  privateMd,
  profileMd,
  projectsMd,
  stackMd,
  type InitAnswers,
} from "../core/templates.js";
import { bold, cyan, dim, info, ok, warn } from "./ui.js";

const SAMPLE_ANSWERS: InitAnswers = {
  name: "SAMPLE User",
  role: "SAMPLE — placeholder role. Run `dotme init --force` to replace with real answers, or edit these files directly.",
  communication: "SAMPLE — direct, concise, no filler.",
  projects: [
    {
      name: "SAMPLE Project",
      status: "active",
      context: "SAMPLE — placeholder project generated by `dotme init --sample`.",
    },
  ],
  stack: "SAMPLE — e.g. MacBook Pro, VS Code, Node 20, deploys on Vercel.",
  preferences:
    "SAMPLE — e.g. give me the answer first, then the reasoning. Never use emojis.",
};

async function askQuestions(): Promise<InitAnswers & { git?: boolean }> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  const ask = async (q: string): Promise<string | undefined> => {
    const answer = (await rl.question(`${cyan("?")} ${q} ${dim("(Enter to skip)")} `)).trim();
    return answer || undefined;
  };

  console.log(bold("\nLet's set up your ~/.me — every question is skippable.\n"));
  const answers: InitAnswers = {};
  answers.name = await ask("Your name?");
  answers.role = await ask("What do you do? (role, focus, one line)");
  answers.communication = await ask("How do you like to communicate? (e.g. 'direct, no fluff')");

  answers.projects = [];
  console.log(dim("\nActive projects — add as many as you like, blank name to stop."));
  for (;;) {
    const name = await ask(`Project ${answers.projects.length + 1} name?`);
    if (!name) break;
    const status = await ask(`  Status of "${name}"? (e.g. active, launching Friday)`);
    const context = await ask(`  One line of context for "${name}"?`);
    answers.projects.push({ name, status, context });
  }

  answers.stack = await ask("\nYour stack? (machines, editors, languages, infra — one line is fine)");
  answers.preferences = await ask("How should AI tools behave with you? (tone, format, rules)");

  const gitAnswer = (
    await rl.question(
      `${cyan("?")} Make ~/.me a git repo? private.md and .changelog will be gitignored. ${dim("(y/N)")} `,
    )
  )
    .trim()
    .toLowerCase();

  rl.close();
  return { ...answers, git: gitAnswer.startsWith("y") };
}

export async function init(args: string[]): Promise<void> {
  const sample = args.includes("--sample");
  const force = args.includes("--force");
  const dir = meDir();

  if (meExists() && !force) {
    warn(`${dir} already exists. Use \`dotme init --force\` to overwrite it, or edit the files directly.`);
    process.exitCode = 1;
    return;
  }

  const answers: InitAnswers & { git?: boolean } = sample
    ? SAMPLE_ANSWERS
    : await askQuestions();

  fs.mkdirSync(dir, { recursive: true });
  const files: Record<string, string> = {
    "profile.md": profileMd(answers),
    "projects.md": projectsMd(answers),
    "stack.md": stackMd(answers),
    "preferences.md": preferencesMd(answers),
    "memory.md": memoryMd(),
    "private.md": privateMd(),
  };
  for (const [name, content] of Object.entries(files)) {
    fs.writeFileSync(path.join(dir, name), content);
  }
  saveManifest({
    version: 1,
    created: new Date().toISOString(),
    permissions: defaultPermissions(),
  });
  appendChangelog("dotme-cli", "*", sample ? "initialized ~/.me with --sample data" : "initialized ~/.me");

  const alreadyGit = fs.existsSync(path.join(dir, ".git"));
  if (alreadyGit) {
    info("~/.me is already a git repo — leaving it as is.");
  } else if (answers.git) {
    fs.writeFileSync(path.join(dir, ".gitignore"), GITIGNORE);
    try {
      execFileSync("git", ["init"], { cwd: dir, stdio: "ignore" });
      ok("Initialized ~/.me as a git repo (private.md and .changelog are gitignored).");
    } catch {
      warn("git init failed — is git installed? Skipping.");
    }
  }

  console.log();
  ok(`Created ${bold(dir)}`);
  for (const name of Object.keys(files)) info(`${name}${name === "private.md" ? dim("  (never exposed by default)") : ""}`);
  info(`manifest.json  ${dim("(permissions map)")}`);
  info(`${CHANGELOG_FILE}     ${dim("(audit log of every AI write)")}`);
  console.log(`\nNext: ${bold("dotme connect all")} to hook up Claude Desktop, Claude Code, and Cursor.`);
}
